name: ProjectKorraItems
author: ProjectKorraItems
version: 1.5
main: com.projectkorra.items.ProjectKorraItems
depend: [ProjectKorra]
api-version: 1.13

permissions:
  bendingitems.admin:
    default: op
    description: Grants access to all commands.
    children:
      bendingitems.player: true
      bendingitems.command.reload: true
      bendingitems.command.give: true
  bendingitems.player:
    default: true
    description: Grants access to most commands.
    children:
      bendingitems.command.list: true
      bendingitems.command.stats: true
      bendingitems.command.items: true
      bendingitems.command.equip: true